# Generated by Django 3.0.4 on 2020-03-27 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('org', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('link', models.CharField(max_length=100)),
            ],
        ),
    ]
